info:
    component: 'Ticketservice'

spring:
    application:
        name: tickets
    zipkin:
      baseUrl: 10.1.101.6:9411

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG



---
# For deployment without Docker containers
spring:
  profiles: default

server:
    port: 8080


---
# For deployment in Docker containers
spring:
  profiles: docker

server:
    port: 80