info:
    component: 'Ticketservice'

spring:
    application:
        name: tickets

---
# For deployment without Docker containers
spring:
  profiles: default

server:
    port: 8080


---
# For deployment in Docker containers
spring:
  profiles: docker

server:
    port: 80