info:
  component: 'Composite Service'

spring:
    application:
        name: events

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false
    info:
      enabled: true

server:
    port: 8083

---
# For deployment without Docker containers
spring:
  profiles: default

hostnames:
  events: localhost:8082
  locations: localhost:8081
  tickets: localhost:8080


---
# For deployment in Docker containers
spring:
  profiles: docker

hostnames:
  events: events
  locations: locations
  tickets: tickets