info:
  component: 'Eventservice'

spring:
    application:
        name: events

---
# For deployment without Docker containers
spring:
  profiles: default

server:
    port: 8082


---
# For deployment in Docker containers
spring:
  profiles: docker

server:
    port: 80