info:
  component: 'Locationservice'

spring:
    application:
        name: locations

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false
    info:
      enabled: true

---
# For deployment without Docker containers
spring:
  profiles: default

server:
    port: 8081


---
# For deployment in Docker containers
spring:
  profiles: docker

server:
    port: 80